In [1]:
import os
import re
import pandas as pd
from Bio.PDB import *
from Bio import SeqIO
import nglview as nv
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 100)

The objective of this notebook is to obtain the dataset that contains the epitope residue sequences based on the distance betweem CDR residues and antigen residues.

# 1. Get Metadata

## 1.1 Load summary file

In [14]:
metadata = pd.read_csv('sabdab-data/20221001_0807534_summary.tsv', sep='\t')
len(metadata.pdb.unique())

740

# 1.2 Filter out structure with Hapten Antigen

In [3]:
metadata = metadata[metadata['antigen_type']!='Hapten']
len(metadata.pdb.unique())

672

# 2. Get Ab-Ag residue distances
1. From every PDB calculate the distance between the alpha carbon (CA) of the Ab residues in CDR regions and the CA of every Ag residue, but keep only those under 15 Angstroms (Å). 15Å was chosen because, based on previous data exploration, it is believed that paratope-epitope contacts occur within this distance.
2. From all the calculated distances under 15Å most of the Ab-Ag residue comparison will be outside of the paratope-epitope region; therfore, based on the distance distributions, we will narrow down Ab-Ag residues pairs to get the Ab-Ag residues of interest.

## 2.1 Get PDB IDs

In [4]:
pdb_ids = metadata.pdb.unique()
len(pdb_ids)

672

## 2.2 Calculate distances and keep distances under 15Å

In [5]:
def ab_res_seqid_is_cdr(ab_res_seqid):
    '''
    Returns whether an antibody residue sequence ID is in a CDR region.

    Parameters
    ----------
    ab_res_seqid : int
        IMGT sequence identifier (obtained from the get_id() function of 
    the residue object in Bio.PDB module of BioPython.)

    Output
    ------
    is_cdr : bool
        True if the antibody residue sequence ID is in a CDR region and False otherwise.
    cdr_region : str
        The CDR region the ab_res_seqid belongs to ('CDR1','CDR2','CDR3') or an empty 
    string if it doesn't belong to any CDR region.
    '''
    cdr1_start = 27
    cdr1_end = 38
    cdr2_start = 56
    cdr2_end = 65
    cdr3_start = 105
    cdr3_end = 117

    if cdr1_start <= ab_res_seqid and ab_res_seqid <= cdr1_end:
        is_cdr = True
        cdr_region = 'CDR1'
    elif cdr2_start <= ab_res_seqid and ab_res_seqid <= cdr2_end:
        is_cdr = True
        cdr_region = 'CDR2'
    elif cdr2_start <= ab_res_seqid and ab_res_seqid <= cdr2_end:
        is_cdr = True
        cdr_region = 'CDR3'
    else:
        is_cdr = False
        cdr_region = ''
    return is_cdr, cdr_region

def get_ab_ag_distances(model, Ab_labels, Ag_labels, max_dist=15):
    '''
    Returns a dictionary with the Ab-Ag distances as well as other identifier information.
    '''
    distances = []
    ab_ress = []
    ag_ress = []
    ab_seqids = []
    ag_seqids = []
    ab_labels = []
    ag_labels = []
    cdr_regions = []
    comparison_num = 0
    for ab_label in Ab_labels:
        Ab_ch = model[ab_label]
        for ab_res in Ab_ch.get_residues():
            ab_res_name = ab_res.get_resname()
            ab_res_het_tag, ab_seqid, ab_insertion = ab_res.get_id()
            if ab_res_het_tag == ' ' or ab_res_het_tag == '':
                ab_atom = ab_res['CA']
                for ag_label in Ag_labels:
                    Ag_ch = model[ag_label]
                    for ag_res in Ag_ch.get_residues():
                        ag_res_name = ag_res.get_resname()
                        ag_res_het_tag, ag_seqid, ag_insertion = ag_res.get_id()
                        if ag_res_het_tag == ' ' or ag_res_het_tag == '':
                            ag_atom = ag_res['CA']
                            dist = ab_atom - ag_atom
                            is_cdr, cdr_region = ab_res_seqid_is_cdr(ab_seqid)
                            if is_cdr and (ab_label in Ab_labels) and (dist<=max_dist):
                                #print(ab_label,ab_res_name, ab_res.get_id(), is_cdr)
                                ab_ress.append(ab_res_name)
                                ag_ress.append(ag_res_name)
                                ab_seqids.append(ab_seqid)
                                ag_seqids.append(ag_seqid)
                                ab_labels.append(ab_label)
                                ag_labels.append(ag_label)
                                cdr_regions.append(cdr_region)
                                distances.append(dist) 
                                comparison_num += 1
                                if comparison_num % 100 == 0:
                                    print(f'{comparison_num} comparisons made so far.')

    

    print(f'{comparison_num} total comparisons')
    print('Finished...')
    comparisons_dict = {'ab_label':ab_labels,'ab_res':ab_ress,'ab_seqid':ab_seqids,'ag_label':ag_labels,'ag_res':ag_ress,'ag_seqid':ag_seqids,'distances':distances}
    return comparisons_dict

In [15]:
# TODO: This code is a brute-force code. Make code more efficient.
count = 0
pending_pdbs = {'pdb':[],'error':[]} #PDBs that can't be processed because an error occurs
n_closest_ag_ress = 6
for pdb in pdb_ids[0:1]:
    print(f'{count}.- Analyzing pdb {pdb}')
    # Parse pdb
    pdb_parser = PDBParser()
    structure = pdb_parser.get_structure(pdb, "sabdab-data/imgt/{}.pdb".format(pdb))

    # Get chains
    chain_label_list = []
    for model in structure.get_models():
        for chain in model.get_chains():
            chain_label_list.append(chain.get_id())

    # The label given to the H and L chains in the PDB
    H_labels = list(metadata[(metadata['pdb']==pdb)&(~metadata.Hchain.isna())].Hchain.values)
    L_labels = list(metadata[(metadata['pdb']==pdb)&(~metadata.Lchain.isna())].Lchain.values)

    Ab_labels = H_labels + L_labels

    if not metadata[(metadata['pdb']==pdb)&(~metadata.antigen_chain.isnull())].empty:
        Ag_labels = list(metadata[metadata['pdb']==pdb].antigen_chain.values)
        if len(Ag_labels) == 1:
            Ag_labels = re.findall('[A-Z]',Ag_labels[0])
    else:
        Ag_labels = []
        for label in chain_label_list:
            if label not in H_labels and label not in L_labels:
                Ag_labels.append(label)

    try:
        comparisons_dict = get_ab_ag_distances(model, Ab_labels, Ag_labels, 15)

        comparisons_df = pd.DataFrame(comparisons_dict)

        if comparisons_df.empty:
            print(f'Empty comparisons_df with pdb {pdb}')
        else:
            comparisons_df['ab_ress_seqid'] = comparisons_df.ab_res + '-' + comparisons_df.ab_seqid.astype(str)
            comparisons_df['ag_ress_seqid'] = comparisons_df.ag_res + '-' + comparisons_df.ag_seqid.astype(str)
            comparisons_df['pdb'] = pdb
            distances_df = comparisons_df.groupby('ab_ress_seqid').apply(lambda df: df.nlargest(n_closest_ag_ress, columns='distances')).reset_index(level=[0,1], drop=True)
            distances_df.sort_values(['ab_ress_seqid','distances','ag_ress_seqid'],inplace=True)
            if not os.path.exists('distances.csv'):
                distances_df.to_csv('distances.csv',index=False, )
            else:
                distances_df.to_csv('distances.csv',mode='a',index=False,header=False)
    
    except Exception as e:
        pending_pdbs['pdb'].append(pdb)
        pending_pdbs['error'].append(e)

    print('\n')
    if count%50 == 0:
        print(f'Analyzed {count} PDBs so far.')
    count += 1

pending_pdbs_df = pd.DataFrame(pending_pdbs)
pending_pdbs_df.to_csv('pending_pdbs.csv')
print('Finished...')

0.- Analyzing pdb 1mhh
0 total comparisons
Finished...
Empty comparisons_df with pdb 1mhh


Analyzed 0 PDBs so far.
Finished...

These are the PDBs that were not processed due to errors.

In [7]:
pending_pdbs_df.error.unique()

array([], dtype=float64)

# 3. Check distances

In [8]:
distances_df = pd.read_csv('distances.csv')

In [9]:
len(distances_df)

1343

In [10]:
distances_df.head(20)

,ab_label,ab_res,ab_seqid,ag_label,ag_res,ag_seqid,distances,ab_ress_seqid,ag_ress_seqid,pdb
0,A,ALA,57,C,GLU,5,11.268807,ALA-57,GLU-5,1hh9
1,A,ALA,57,C,ALA,2,12.260887,ALA-57,ALA-2,1hh9
2,A,ALA,57,C,LEU,7,12.740383,ALA-57,LEU-7,1hh9
3,A,ALA,57,C,THR,3,13.943336,ALA-57,THR-3,1hh9
4,A,ALA,57,C,PRO,4,14.627425,ALA-57,PRO-4,1hh9
5,A,ALA,57,C,ASP,1,14.756581,ALA-57,ASP-1,1hh9
6,A,ARG,56,C,LEU,7,9.369978,ARG-56,LEU-7,1hh9
7,A,ARG,56,C,THR,3,10.328367,ARG-56,THR-3,1hh9
8,A,ARG,56,C,PRO,4,10.817346,ARG-56,PRO-4,1hh9
9,A,ARG,56,C,ASP,1,12.066611,ARG-56,ASP-1,1hh9
10,A,ARG,56,C,ASN,8,12.633677,ARG-56,ASN-8,1hh9
11,A,ARG,56,C,ALA,9,14.927403,ARG-56,ALA-9,1hh9
12,A,ASN,36,C,LEU,7,10.679121,ASN-36,LEU-7,1hh9
13,A,ASN,36,C,GLU,5,11.493199,ASN-36,GLU-5,1hh9
14,A,ASN,36,C,ASP,6,11.763302,ASN-36,ASP-6,1hh9
15,A,ASN,36,C,ASN,8,14.371833,ASN-36,ASN-8,1hh9
16,A,ASN,36,C,ALA,9,14.464322,ASN-36,ALA-9,1hh9
17,A,ASN,65,C,ALA,2,11.765996,ASN-65,ALA-2,1hh9
18,A,ASN,65,C,GLU,5,12.411185,ASN-65,GLU-5,1hh9
19,A,ASN,65,C,ASP,6,12.731392,ASN-65,ASP-6,1hh9

In [11]:
distances_df.groupby(['pdb','ab_ress_seqid']).count()

                    ab_label  ab_res  ab_seqid  ag_label  ag_res  ag_seqid  \
pdb  ab_ress_seqid
1hh9 ALA-57                6       6         6         6       6         6
     ARG-56                6       6         6         6       6         6
     ASN-36                5       5         5         5       5         5
     ASN-65                5       5         5         5       5         5
     ASP-28                1       1         1         1       1         1
...                      ...     ...       ...       ...     ...       ...
6h0e SER-35                4       4         4         4       4         4
     SER-62                6       6         6         6       6         6
     THR-65                6       6         6         6       6         6
     TYR-37                6       6         6         6       6         6
     TYR-38                6       6         6         6       6         6

                    distances  ag_ress_seqid
pdb  ab_ress_seqid
1hh9 ALA-57                 6              6
     ARG-56                 6              6
     ASN-36                 5              5
     ASN-65                 5              5
     ASP-28                 1              1
...                       ...            ...
6h0e SER-35                 4              4
     SER-62                 6              6
     THR-65                 6              6
     TYR-37                 6              6
     TYR-38                 6              6

[237 rows x 8 columns]